apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.scrapeInterval }}

    scrape_configs:
      - job_name: fastapi
        static_configs:
          - targets: ["multiagent-app:{{ .Values.app.port }}"]
        metrics_path: /metrics

      - job_name: prometheus
        static_configs:
          - targets: ["localhost:{{ .Values.prometheus.port }}"]
