apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      protocol: TCP
      nodePort: 30900
