version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: multiagent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://postgres:1234@postgres:5432/multiagent
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts mlflow
      --allowed-hosts localhost
      --allowed-hosts app
      --allowed-hosts 127.0.0.1
      --allowed-hosts *
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    container_name: multiagent-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - .:/app 
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: multiagent-frontend
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - app
    restart: unless-stopped      

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs:/logs
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  prometheus:
    
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

volumes:
  postgres_data:
  mlflow_data:
  grafana_data: