apiVersion: v1
kind: Secret
metadata:
  name: multiagent-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GROQ_API_KEY:        {{ .Values.secrets.groqApiKey | quote }}
  POSTGRES_PASSWORD:   {{ .Values.secrets.postgresPassword | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
