_CATEGORY_NORM = {
    "electronics": "Electronics",
    "computers&accessories": "Computers&Accessories",
    "computers & accessories": "Computers&Accessories",
    "computers and accessories": "Computers&Accessories",
    "computers": "Computers&Accessories",
    "home&kitchen": "Home&Kitchen",
    "home & kitchen": "Home&Kitchen",
    "home and kitchen": "Home&Kitchen",
    "kitchen": "Home&Kitchen",
    "home": "Home&Kitchen",
}

BRAND_MAP = {
    "hp": "HP",
    "dell": "Dell",
    "apple": "Apple",
    "samsung": "Samsung",
    "sony": "Sony",
    "lenovo": "Lenovo",
    "oneplus": "OnePlus",
    "boat": "boAt",
    "asus": "ASUS",
    "acer": "Acer",
    "mi": "Mi",
    "realme": "Realme",
    "redmi": "Redmi",
    "motorola": "Motorola",
    "nokia": "Nokia",
    "oppo": "OPPO",
    "vivo": "Vivo",
    "google": "Google",
    "lg": "LG",
    "panasonic": "Panasonic",
    "philips": "Philips",
    "bajaj": "Bajaj",
    "prestige": "Prestige",
    "daikin": "Daikin",
    "voltas": "Voltas",
    "whirlpool": "Whirlpool",
    "bosch": "Bosch",
    "kent": "Kent",
    "aquaguard": "Aquaguard",
    "havells": "Havells",
    "instant": "Instant",
    "tefal": "Tefal",
    "milton": "Milton",
    "pigeon": "Pigeon",
    "hawkins": "Hawkins",
    "cello": "Cello",
    "borosil": "Borosil",
    "butterfly": "Butterfly",
    "vinod": "Vinod",
    "ifb": "IFB",
    "tcl": "TCL",
    "hisense": "Hisense",
    "logitech": "Logitech",
    "razer": "Razer",
    "zebronics": "Zebronics",
    "portronics": "Portronics",
    "bose": "Bose",
    "jbl": "JBL",
    "sennheiser": "Sennheiser",
    "jabra": "Jabra",
    "noise": "Noise",
    "boult": "Boult",
    "skullcandy": "Skullcandy",
    "hyperx": "HyperX",
    "keychron": "Keychron",
    "aoc": "AOC",
    "benq": "BenQ",
    "canon": "Canon",
    "epson": "Epson",
    "gopro": "GoPro",
    "wd": "WD",
    "seagate": "Seagate",
    "kingston": "Kingston",
    "crucial": "Crucial",
    "anker": "Anker",
    "ambrane": "Ambrane",
    "syska": "Syska",
    "belkin": "Belkin",
    "baseus": "Baseus",
    "inalsa": "INALSA",
    "cosori": "Cosori",
    "agaro": "AGARO",
    "sujata": "Sujata",
    "morphy": "Morphy Richards",
    "delonghi": "De'Longhi",
    "nescafe": "Nescafe",
    "nutribullet": "Nutribullet",
    "ao smith": "AO Smith",
    "hul": "HUL",
    "voltas": "Voltas",
    "carrier": "Carrier",
    "hitachi": "Hitachi",
    "blue star": "Blue Star",
}

_GENERIC_WORDS = {
    "product",
    "products",
    "item",
    "items",
    "thing",
    "things",
    "anything",
    "something",
    "goods",
    "appliance",
    "appliances",
    "none",
}

# Used for follow-up carry-forward: scan history for these product-type terms
_CARRY_PRODUCT_TYPES = [
    "laptop",
    "phone",
    "smartphone",
    "tablet",
    "tv",
    "television",
    "camera",
    "watch",
    "smartwatch",
    "earphone",
    "headphone",
    "earbuds",
    "earbud",
    "speaker",
    "neckband",
    "headset",
    "keyboard",
    "mouse",
    "monitor",
    "charger",
    "cable",
    "mixer grinder",
    "air conditioner",
    "washing machine",
    "water purifier",
    "microwave",
    "air fryer",
    "electric kettle",
    "kettle",
    "rice cooker",
    "refrigerator",
    "pressure cooker",
    "water bottle",
    "coffee maker",
    "blender",
    "juicer",
    "toaster",
    "webcam",
    "printer",
    "ssd",
    "soundbar",
    "induction cooktop",
]
